## Insert Params as you see fit in this file
## test_data - can be public, or private - effects the Time Series Split method. 
## if public will filter out all data 

baseline_model:
  test_model: public
  random_seed: 255

