## Insert Params as you see fit in this file
## test_data - can be public, or private - effects the Time Series Split method. 
## if public will filter out all data 
## if low_memory_mode is true - will run pipeline with only 10000 rows for functionality testing purposes. 

baseline_model:
  test_model: private
  random_seed: 255
  low_memory_mode: False
  use_fin_data: False
  data_date_limit: "2021-01-01
  train_split_date: "2020-01-01"
  test_split_date: "2020-01-01"
  # If we want to drop data from train and test --> Avoid Data leak -> drop 2 months data
  drop_data: False
  drop_data_train_date: "2016-02-01"
  drop_data_test_date: "2020-01-01"
  ridge_regression: False
  alpha: 1.0
  cross_validation: False
  lgb_model: True
  use_test_as_validation: False
  train_with_all_data: True
  seed: 227
  lgb_params: {
      "application": "fair",
      "num_iterations": 130,
      "learning_rate": 0.1,
      "early_stopping_round": 10,
      "feature_fraction": 1.0,
      "bagging_fraction": 0.9,
      "subsample_freq": 1,
      "min_data_in_leaf": 1016,
      "metric": "lgb_spearmanr",
      "num_leaves": 1016,
      "reg_alpha": 0.3899,
      "reg_lambda": 0.648,
      "verbose": -1,
      "device_type": 'cpu'
    }

